In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_excel('test.xlsx',engine='openpyxl')
df

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,1,1,1,2020,01/06/2020,1517.076923,NaN,0,0,0,0
1,2,1,1,2020,01/13/2020,1517.076923,NaN,-9999999,0,0,0
2,3,1,1,2020,01/20/2020,1517.076923,NaN,0,0,0,0
3,4,1,1,2020,01/27/2020,1517.076923,NaN,0,0,0,0
4,5,2,1,2020,02/03/2020,1517.076923,NaN,0,0,0,0
5,6,2,1,2020,02/10/2020,1517.076923,NaN,0,0,0,0
6,7,2,1,2020,02/17/2020,1517.076923,NaN,0,0,0,0
7,8,2,1,2020,02/24/2020,1517.076923,NaN,0,0,0,0
8,9,3,1,2020,03/02/2020,1517.076923,NaN,0,0,0,0
9,10,3,1,2020,03/09/2020,1517.076923,NaN,0,0,0,0
10,11,3,1,2020,03/16/2020,1517.076923,NaN,0,0,0,0
11,12,3,1,2020,03/23/2020,1517.076923,NaN,-9999999,0,0,0
12,13,3,1,2020,03/30/2020,1517.076923,NaN,0,0,0,0
13,14,4,2,2020,04/06/2020,1517.076923,NaN,0,0,0,0
14,15,4,2,2020,04/13/2020,1517.076923,NaN,0,-888888,0,0
15,16,4,2,2020,04/20/2020,1517.076923,NaN,0,0,0,0
16,17,4,2,2020,04/27/2020,1517.076923,NaN,0,0,0,0
17,18,5,2,2020,05/04/2020,1517.076923,NaN,0,0,0,0
18,19,5,2,2020,05/11/2020,1517.076923,NaN,0,0,0,0
19,20,5,2,2020,05/18/2020,1517.076923,NaN,0,0,0,0
20,21,5,2,2020,05/25/2020,1517.076923,NaN,0,0,0,0
21,22,6,2,2020,06/01/2020,1517.076923,NaN,0,0,0,0
22,23,6,2,2020,06/08/2020,1517.076923,NaN,0,0,0,0
23,24,6,2,2020,06/15/2020,1517.076923,NaN,0,0,0,0
24,25,6,2,2020,06/22/2020,1517.076923,NaN,0,0,0,0
25,26,6,2,2020,06/29/2020,1517.076923,NaN,0,0,0,0
26,27,7,3,2020,07/06/2020,1517.076923,NaN,0,0,0,0
27,28,7,3,2020,07/13/2020,1517.076923,NaN,0,0,0,0
28,29,7,3,2020,07/20/2020,1517.076923,NaN,0,0,0,0
29,30,7,3,2020,07/27/2020,1517.076923,NaN,0,0,0,0
30,31,8,3,2020,08/03/2020,1517.076923,NaN,0,0,0,0
31,32,8,3,2020,08/10/2020,1517.076923,NaN,0,0,0,0
32,33,8,3,2020,08/17/2020,1517.076923,NaN,0,0,0,0
33,34,8,3,2020,08/24/2020,1517.076923,NaN,0,0,0,0
34,35,8,3,2020,08/31/2020,1517.076923,NaN,0,0,0,0
35,36,9,3,2020,09/07/2020,1517.076923,NaN,0,0,0,0
36,37,9,3,2020,09/14/2020,1517.076923,NaN,0,0,0,0
37,38,9,3,2020,09/21/2020,1517.076923,NaN,0,0,0,0
38,39,9,3,2020,09/28/2020,1517.076923,NaN,0,0,0,0
39,40,10,4,2020,10/05/2020,1517.076923,NaN,0,0,0,0
40,41,10,4,2020,10/12/2020,1517.076923,NaN,0,0,0,0
41,42,10,4,2020,10/19/2020,1517.076923,NaN,0,0,0,0
42,43,10,4,2020,10/26/2020,1517.076923,NaN,0,0,0,0
43,44,11,4,2020,11/02/2020,1517.076923,NaN,0,0,0,0
44,45,11,4,2020,11/09/2020,1517.076923,NaN,0,0,0,0
45,46,11,4,2020,11/16/2020,1517.076923,NaN,0,0,0,0
46,47,11,4,2020,11/23/2020,1517.076923,NaN,0,0,0,0
47,48,11,4,2020,11/30/2020,1517.076923,NaN,0,0,0,0
48,49,12,4,2020,12/07/2020,1517.076923,NaN,0,0,0,0
49,50,12,4,2020,12/14/2020,1517.076923,NaN,0,0,0,0
50,51,12,4,2020,12/21/2020,1517.076923,NaN,0,0,0,0
51,52,12,4,2020,12/28/2020,1517.076923,NaN,0,0,0,0

In [11]:
df.head(10)

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,1,1,1,2020,01/06/2020,1517.076923,NaN,0,0,0,0
1,2,1,1,2020,01/13/2020,1517.076923,NaN,-9999999,0,0,0
2,3,1,1,2020,01/20/2020,1517.076923,NaN,0,0,0,0
3,4,1,1,2020,01/27/2020,1517.076923,NaN,0,0,0,0
4,5,2,1,2020,02/03/2020,1517.076923,NaN,0,0,0,0
5,6,2,1,2020,02/10/2020,1517.076923,NaN,0,0,0,0
6,7,2,1,2020,02/17/2020,1517.076923,NaN,0,0,0,0
7,8,2,1,2020,02/24/2020,1517.076923,NaN,0,0,0,0
8,9,3,1,2020,03/02/2020,1517.076923,NaN,0,0,0,0
9,10,3,1,2020,03/09/2020,1517.076923,NaN,0,0,0,0

In [12]:
new_df = df.fillna(4)

In [15]:
replaced_df = df.replace(-9999999, np.NAN)
replaced_df.head(10)

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,1,1,1,2020,01/06/2020,1517.076923,NaN,0.0,0,0,0
1,2,1,1,2020,01/13/2020,1517.076923,NaN,NaN,0,0,0
2,3,1,1,2020,01/20/2020,1517.076923,NaN,0.0,0,0,0
3,4,1,1,2020,01/27/2020,1517.076923,NaN,0.0,0,0,0
4,5,2,1,2020,02/03/2020,1517.076923,NaN,0.0,0,0,0
5,6,2,1,2020,02/10/2020,1517.076923,NaN,0.0,0,0,0
6,7,2,1,2020,02/17/2020,1517.076923,NaN,0.0,0,0,0
7,8,2,1,2020,02/24/2020,1517.076923,NaN,0.0,0,0,0
8,9,3,1,2020,03/02/2020,1517.076923,NaN,0.0,0,0,0
9,10,3,1,2020,03/09/2020,1517.076923,NaN,0.0,0,0,0

In [16]:
replaced_df['Neg Exp'].fillna('Special values')

0                  0
1     Special values
2                  0
3                  0
4                  0
5                  0
6                  0
7                  0
8                  0
9                  0
10                 0
11    Special values
12                 0
13                 0
14                 0
15                 0
16                 0
17                 0
18                 0
19                 0
20                 0
21                 0
22                 0
23                 0
24                 0
25                 0
26                 0
27                 0
28                 0
29                 0
30                 0
31                 0
32                 0
33                 0
34                 0
35                 0
36                 0
37                 0
38                 0
39                 0
40                 0
41                 0
42                 0
43                 0
44                 0
45                 0
46                 0
47                 0
48                 0
49                 0
50                 0
51                 0
Name: Neg Exp, dtype: object

In [17]:
new_replaced_df = df.replace({
    "Power": -888888,
    "S Origin": 0
},np.NAN)

In [25]:
new_replaced_df.fillna({
    "S Origin": "no special Event"
})

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,1,1,1,2020,01/06/2020,1517.076923,NaN,0,0.0,no special Event,0
1,2,1,1,2020,01/13/2020,1517.076923,NaN,-9999999,0.0,no special Event,0
2,3,1,1,2020,01/20/2020,1517.076923,NaN,0,0.0,no special Event,0
3,4,1,1,2020,01/27/2020,1517.076923,NaN,0,0.0,no special Event,0
4,5,2,1,2020,02/03/2020,1517.076923,NaN,0,0.0,no special Event,0
5,6,2,1,2020,02/10/2020,1517.076923,NaN,0,0.0,no special Event,0
6,7,2,1,2020,02/17/2020,1517.076923,NaN,0,0.0,no special Event,0
7,8,2,1,2020,02/24/2020,1517.076923,NaN,0,0.0,no special Event,0
8,9,3,1,2020,03/02/2020,1517.076923,NaN,0,0.0,no special Event,0
9,10,3,1,2020,03/09/2020,1517.076923,NaN,0,0.0,no special Event,0
10,11,3,1,2020,03/16/2020,1517.076923,NaN,0,0.0,no special Event,0
11,12,3,1,2020,03/23/2020,1517.076923,NaN,-9999999,0.0,no special Event,0
12,13,3,1,2020,03/30/2020,1517.076923,NaN,0,0.0,no special Event,0
13,14,4,2,2020,04/06/2020,1517.076923,NaN,0,0.0,no special Event,0
14,15,4,2,2020,04/13/2020,1517.076923,NaN,0,NaN,no special Event,0
15,16,4,2,2020,04/20/2020,1517.076923,NaN,0,0.0,no special Event,0
16,17,4,2,2020,04/27/2020,1517.076923,NaN,0,0.0,no special Event,0
17,18,5,2,2020,05/04/2020,1517.076923,NaN,0,0.0,no special Event,0
18,19,5,2,2020,05/11/2020,1517.076923,NaN,0,0.0,no special Event,0
19,20,5,2,2020,05/18/2020,1517.076923,NaN,0,0.0,no special Event,0
20,21,5,2,2020,05/25/2020,1517.076923,NaN,0,0.0,no special Event,0
21,22,6,2,2020,06/01/2020,1517.076923,NaN,0,0.0,no special Event,0
22,23,6,2,2020,06/08/2020,1517.076923,NaN,0,0.0,no special Event,0
23,24,6,2,2020,06/15/2020,1517.076923,NaN,0,0.0,no special Event,0
24,25,6,2,2020,06/22/2020,1517.076923,NaN,0,0.0,no special Event,0
25,26,6,2,2020,06/29/2020,1517.076923,NaN,0,0.0,no special Event,0
26,27,7,3,2020,07/06/2020,1517.076923,NaN,0,0.0,no special Event,0
27,28,7,3,2020,07/13/2020,1517.076923,NaN,0,0.0,no special Event,0
28,29,7,3,2020,07/20/2020,1517.076923,NaN,0,0.0,no special Event,0
29,30,7,3,2020,07/27/2020,1517.076923,NaN,0,0.0,no special Event,0
30,31,8,3,2020,08/03/2020,1517.076923,NaN,0,0.0,no special Event,0
31,32,8,3,2020,08/10/2020,1517.076923,NaN,0,0.0,no special Event,0
32,33,8,3,2020,08/17/2020,1517.076923,NaN,0,0.0,no special Event,0
33,34,8,3,2020,08/24/2020,1517.076923,NaN,0,0.0,no special Event,0
34,35,8,3,2020,08/31/2020,1517.076923,NaN,0,0.0,no special Event,0
35,36,9,3,2020,09/07/2020,1517.076923,NaN,0,0.0,no special Event,0
36,37,9,3,2020,09/14/2020,1517.076923,NaN,0,0.0,no special Event,0
37,38,9,3,2020,09/21/2020,1517.076923,NaN,0,0.0,no special Event,0
38,39,9,3,2020,09/28/2020,1517.076923,NaN,0,0.0,no special Event,0
39,40,10,4,2020,10/05/2020,1517.076923,NaN,0,0.0,no special Event,0
40,41,10,4,2020,10/12/2020,1517.076923,NaN,0,0.0,no special Event,0
41,42,10,4,2020,10/19/2020,1517.076923,NaN,0,0.0,no special Event,0
42,43,10,4,2020,10/26/2020,1517.076923,NaN,0,0.0,no special Event,0
43,44,11,4,2020,11/02/2020,1517.076923,NaN,0,0.0,no special Event,0
44,45,11,4,2020,11/09/2020,1517.076923,NaN,0,0.0,no special Event,0
45,46,11,4,2020,11/16/2020,1517.076923,NaN,0,0.0,no special Event,0
46,47,11,4,2020,11/23/2020,1517.076923,NaN,0,0.0,no special Event,0
47,48,11,4,2020,11/30/2020,1517.076923,NaN,0,0.0,no special Event,0
48,49,12,4,2020,12/07/2020,1517.076923,NaN,0,0.0,no special Event,0
49,50,12,4,2020,12/14/2020,1517.076923,NaN,0,0.0,no special Event,0
50,51,12,4,2020,12/21/2020,1517.076923,NaN,0,0.0,no special Event,0
51,52,12,4,2020,12/28/2020,1517.076923,NaN,0,0.0,no special Event,0

In [27]:
t = new_replaced_df.replace({
    -9999999 : 0.0,
    'no special Event': 'Sunny'
})

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,1.0,1.0,1.0,2020.0,01/06/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
1,2.0,1.0,1.0,2020.0,01/13/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
2,3.0,1.0,1.0,2020.0,01/20/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
3,4.0,1.0,1.0,2020.0,01/27/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
4,5.0,2.0,1.0,2020.0,02/03/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
5,6.0,2.0,1.0,2020.0,02/10/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
6,7.0,2.0,1.0,2020.0,02/17/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
7,8.0,2.0,1.0,2020.0,02/24/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
8,9.0,3.0,1.0,2020.0,03/02/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
9,10.0,3.0,1.0,2020.0,03/09/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
10,11.0,3.0,1.0,2020.0,03/16/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
11,12.0,3.0,1.0,2020.0,03/23/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
12,13.0,3.0,1.0,2020.0,03/30/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
13,14.0,4.0,2.0,2020.0,04/06/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
14,15.0,4.0,2.0,2020.0,04/13/2020,1517.076923,NaN,0.0,NaN,NaN,0.0
15,16.0,4.0,2.0,2020.0,04/20/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
16,17.0,4.0,2.0,2020.0,04/27/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
17,18.0,5.0,2.0,2020.0,05/04/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
18,19.0,5.0,2.0,2020.0,05/11/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
19,20.0,5.0,2.0,2020.0,05/18/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
20,21.0,5.0,2.0,2020.0,05/25/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
21,22.0,6.0,2.0,2020.0,06/01/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
22,23.0,6.0,2.0,2020.0,06/08/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
23,24.0,6.0,2.0,2020.0,06/15/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
24,25.0,6.0,2.0,2020.0,06/22/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
25,26.0,6.0,2.0,2020.0,06/29/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
26,27.0,7.0,3.0,2020.0,07/06/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
27,28.0,7.0,3.0,2020.0,07/13/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
28,29.0,7.0,3.0,2020.0,07/20/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
29,30.0,7.0,3.0,2020.0,07/27/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
30,31.0,8.0,3.0,2020.0,08/03/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
31,32.0,8.0,3.0,2020.0,08/10/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
32,33.0,8.0,3.0,2020.0,08/17/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
33,34.0,8.0,3.0,2020.0,08/24/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
34,35.0,8.0,3.0,2020.0,08/31/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
35,36.0,9.0,3.0,2020.0,09/07/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
36,37.0,9.0,3.0,2020.0,09/14/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
37,38.0,9.0,3.0,2020.0,09/21/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
38,39.0,9.0,3.0,2020.0,09/28/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
39,40.0,10.0,4.0,2020.0,10/05/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
40,41.0,10.0,4.0,2020.0,10/12/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
41,42.0,10.0,4.0,2020.0,10/19/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
42,43.0,10.0,4.0,2020.0,10/26/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
43,44.0,11.0,4.0,2020.0,11/02/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
44,45.0,11.0,4.0,2020.0,11/09/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
45,46.0,11.0,4.0,2020.0,11/16/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
46,47.0,11.0,4.0,2020.0,11/23/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
47,48.0,11.0,4.0,2020.0,11/30/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
48,49.0,12.0,4.0,2020.0,12/07/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
49,50.0,12.0,4.0,2020.0,12/14/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
50,51.0,12.0,4.0,2020.0,12/21/2020,1517.076923,NaN,0.0,0.0,NaN,0.0
51,52.0,12.0,4.0,2020.0,12/28/2020,1517.076923,NaN,0.0,0.0,NaN,0.0