In [5]:
import pandas as pd

In [56]:
df = pd.read_excel('test.xlsx',engine='openpyxl')

In [57]:
r, c = df.shape
print(r)
print(c)
print(df.columns)

52
11
Index(['Week Number', 'Month', 'Quarter', 'Year', 'Week Start', 'Linear',
       'Log', 'Neg Exp', 'Power', 'S Origin', 'S Shaped'],
      dtype='object')

In [58]:
df.head(10)

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,1,1,1,2020,01/06/2020,1517.076923,0,0,0,0,0
1,2,1,1,2020,01/13/2020,1517.076923,0,0,0,0,0
2,3,1,1,2020,01/20/2020,1517.076923,0,0,0,0,0
3,4,1,1,2020,01/27/2020,1517.076923,0,0,0,0,0
4,5,2,1,2020,02/03/2020,1517.076923,0,0,0,0,0
5,6,2,1,2020,02/10/2020,1517.076923,0,0,0,0,0
6,7,2,1,2020,02/17/2020,1517.076923,0,0,0,0,0
7,8,2,1,2020,02/24/2020,1517.076923,0,0,0,0,0
8,9,3,1,2020,03/02/2020,1517.076923,0,0,0,0,0
9,10,3,1,2020,03/09/2020,1517.076923,0,0,0,0,0

In [59]:
df.tail(5)

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
47,48,11,4,2020,11/30/2020,1517.076923,0,0,0,0,0
48,49,12,4,2020,12/07/2020,1517.076923,0,0,0,0,0
49,50,12,4,2020,12/14/2020,1517.076923,0,0,0,0,0
50,51,12,4,2020,12/21/2020,1517.076923,0,0,0,0,0
51,52,12,4,2020,12/28/2020,1517.076923,0,0,0,0,0

In [60]:
df[2:5]

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
2,3,1,1,2020,01/20/2020,1517.076923,0,0,0,0,0
3,4,1,1,2020,01/27/2020,1517.076923,0,0,0,0,0
4,5,2,1,2020,02/03/2020,1517.076923,0,0,0,0,0

In [61]:
df[::-2]

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
51,52,12,4,2020,12/28/2020,1517.076923,0,0,0,0,0
49,50,12,4,2020,12/14/2020,1517.076923,0,0,0,0,0
47,48,11,4,2020,11/30/2020,1517.076923,0,0,0,0,0
45,46,11,4,2020,11/16/2020,1517.076923,0,0,0,0,0
43,44,11,4,2020,11/02/2020,1517.076923,0,0,0,0,0
41,42,10,4,2020,10/19/2020,1517.076923,0,0,0,0,0
39,40,10,4,2020,10/05/2020,1517.076923,0,0,0,0,0
37,38,9,3,2020,09/21/2020,1517.076923,0,0,0,0,0
35,36,9,3,2020,09/07/2020,1517.076923,0,0,0,0,0
33,34,8,3,2020,08/24/2020,1517.076923,0,0,0,0,0
31,32,8,3,2020,08/10/2020,1517.076923,0,0,0,0,0
29,30,7,3,2020,07/27/2020,1517.076923,0,0,0,0,0
27,28,7,3,2020,07/13/2020,1517.076923,0,0,0,0,0
25,26,6,2,2020,06/29/2020,1517.076923,0,0,0,0,0
23,24,6,2,2020,06/15/2020,1517.076923,0,0,0,0,0
21,22,6,2,2020,06/01/2020,1517.076923,0,0,0,0,0
19,20,5,2,2020,05/18/2020,1517.076923,0,0,0,0,0
17,18,5,2,2020,05/04/2020,1517.076923,0,0,0,0,0
15,16,4,2,2020,04/20/2020,1517.076923,0,0,0,0,0
13,14,4,2,2020,04/06/2020,1517.076923,0,0,0,0,0
11,12,3,1,2020,03/23/2020,1517.076923,0,0,0,0,0
9,10,3,1,2020,03/09/2020,1517.076923,0,0,0,0,0
7,8,2,1,2020,02/24/2020,1517.076923,0,0,0,0,0
5,6,2,1,2020,02/10/2020,1517.076923,0,0,0,0,0
3,4,1,1,2020,01/27/2020,1517.076923,0,0,0,0,0
1,2,1,1,2020,01/13/2020,1517.076923,0,0,0,0,0

In [62]:
df['Week Number'].max()

52

In [63]:
df['Week Number'].min()

1

In [64]:
df.describe()

,Week Number,Month,Quarter,Year,Linear,Log,Neg Exp,Power,S Origin,S Shaped
count,52.000000,52.000000,52.000000,52.0,5.200000e+01,52.0,52.0,52.0,52.0,52.0
mean,26.500000,6.538462,2.500000,2020.0,1.517077e+03,0.0,0.0,0.0,0.0,0.0
std,15.154757,3.449703,1.128942,0.0,6.887760e-13,0.0,0.0,0.0,0.0,0.0
min,1.000000,1.000000,1.000000,2020.0,1.517077e+03,0.0,0.0,0.0,0.0,0.0
25%,13.750000,3.750000,1.750000,2020.0,1.517077e+03,0.0,0.0,0.0,0.0,0.0
50%,26.500000,6.500000,2.500000,2020.0,1.517077e+03,0.0,0.0,0.0,0.0,0.0
75%,39.250000,9.250000,3.250000,2020.0,1.517077e+03,0.0,0.0,0.0,0.0,0.0
max,52.000000,12.000000,4.000000,2020.0,1.517077e+03,0.0,0.0,0.0,0.0,0.0

In [65]:
df.head(10)

,Week Number,Month,Quarter,Year,Week Start,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,1,1,1,2020,01/06/2020,1517.076923,0,0,0,0,0
1,2,1,1,2020,01/13/2020,1517.076923,0,0,0,0,0
2,3,1,1,2020,01/20/2020,1517.076923,0,0,0,0,0
3,4,1,1,2020,01/27/2020,1517.076923,0,0,0,0,0
4,5,2,1,2020,02/03/2020,1517.076923,0,0,0,0,0
5,6,2,1,2020,02/10/2020,1517.076923,0,0,0,0,0
6,7,2,1,2020,02/17/2020,1517.076923,0,0,0,0,0
7,8,2,1,2020,02/24/2020,1517.076923,0,0,0,0,0
8,9,3,1,2020,03/02/2020,1517.076923,0,0,0,0,0
9,10,3,1,2020,03/09/2020,1517.076923,0,0,0,0,0

In [68]:
df[df['Linear'] == df['Linear'].max()]

,Week Number,Month,Quarter,Year,Linear,Log,Neg Exp,Power,S Origin,S Shaped
Week Start,,,,,,,,,,
01/06/2020,1,1,1,2020,1517.076923,0,0,0,0,0
01/13/2020,2,1,1,2020,1517.076923,0,0,0,0,0
01/20/2020,3,1,1,2020,1517.076923,0,0,0,0,0
01/27/2020,4,1,1,2020,1517.076923,0,0,0,0,0
02/03/2020,5,2,1,2020,1517.076923,0,0,0,0,0
02/10/2020,6,2,1,2020,1517.076923,0,0,0,0,0
02/17/2020,7,2,1,2020,1517.076923,0,0,0,0,0
02/24/2020,8,2,1,2020,1517.076923,0,0,0,0,0
03/02/2020,9,3,1,2020,1517.076923,0,0,0,0,0
03/09/2020,10,3,1,2020,1517.076923,0,0,0,0,0
03/16/2020,11,3,1,2020,1517.076923,0,0,0,0,0
03/23/2020,12,3,1,2020,1517.076923,0,0,0,0,0
03/30/2020,13,3,1,2020,1517.076923,0,0,0,0,0
04/06/2020,14,4,2,2020,1517.076923,0,0,0,0,0
04/13/2020,15,4,2,2020,1517.076923,0,0,0,0,0
04/20/2020,16,4,2,2020,1517.076923,0,0,0,0,0
04/27/2020,17,4,2,2020,1517.076923,0,0,0,0,0
05/04/2020,18,5,2,2020,1517.076923,0,0,0,0,0
05/11/2020,19,5,2,2020,1517.076923,0,0,0,0,0
05/18/2020,20,5,2,2020,1517.076923,0,0,0,0,0
05/25/2020,21,5,2,2020,1517.076923,0,0,0,0,0
06/01/2020,22,6,2,2020,1517.076923,0,0,0,0,0
06/08/2020,23,6,2,2020,1517.076923,0,0,0,0,0
06/15/2020,24,6,2,2020,1517.076923,0,0,0,0,0
06/22/2020,25,6,2,2020,1517.076923,0,0,0,0,0
06/29/2020,26,6,2,2020,1517.076923,0,0,0,0,0
07/06/2020,27,7,3,2020,1517.076923,0,0,0,0,0
07/13/2020,28,7,3,2020,1517.076923,0,0,0,0,0
07/20/2020,29,7,3,2020,1517.076923,0,0,0,0,0
07/27/2020,30,7,3,2020,1517.076923,0,0,0,0,0
08/03/2020,31,8,3,2020,1517.076923,0,0,0,0,0
08/10/2020,32,8,3,2020,1517.076923,0,0,0,0,0
08/17/2020,33,8,3,2020,1517.076923,0,0,0,0,0
08/24/2020,34,8,3,2020,1517.076923,0,0,0,0,0
08/31/2020,35,8,3,2020,1517.076923,0,0,0,0,0
09/07/2020,36,9,3,2020,1517.076923,0,0,0,0,0
09/14/2020,37,9,3,2020,1517.076923,0,0,0,0,0
09/21/2020,38,9,3,2020,1517.076923,0,0,0,0,0
09/28/2020,39,9,3,2020,1517.076923,0,0,0,0,0
10/05/2020,40,10,4,2020,1517.076923,0,0,0,0,0
10/12/2020,41,10,4,2020,1517.076923,0,0,0,0,0
10/19/2020,42,10,4,2020,1517.076923,0,0,0,0,0
10/26/2020,43,10,4,2020,1517.076923,0,0,0,0,0
11/02/2020,44,11,4,2020,1517.076923,0,0,0,0,0
11/09/2020,45,11,4,2020,1517.076923,0,0,0,0,0
11/16/2020,46,11,4,2020,1517.076923,0,0,0,0,0
11/23/2020,47,11,4,2020,1517.076923,0,0,0,0,0
11/30/2020,48,11,4,2020,1517.076923,0,0,0,0,0
12/07/2020,49,12,4,2020,1517.076923,0,0,0,0,0
12/14/2020,50,12,4,2020,1517.076923,0,0,0,0,0
12/21/2020,51,12,4,2020,1517.076923,0,0,0,0,0
12/28/2020,52,12,4,2020,1517.076923,0,0,0,0,0

In [76]:
df.set_index('Week Start', inplace=True)

In [78]:
df.loc['12/28/2020']
df

,index,Week Number,Month,Quarter,Year,Linear,Log,Neg Exp,Power,S Origin,S Shaped
Week Start,,,,,,,,,,,
01/06/2020,0,1,1,1,2020,1517.076923,0,0,0,0,0
01/13/2020,1,2,1,1,2020,1517.076923,0,0,0,0,0
01/20/2020,2,3,1,1,2020,1517.076923,0,0,0,0,0
01/27/2020,3,4,1,1,2020,1517.076923,0,0,0,0,0
02/03/2020,4,5,2,1,2020,1517.076923,0,0,0,0,0
02/10/2020,5,6,2,1,2020,1517.076923,0,0,0,0,0
02/17/2020,6,7,2,1,2020,1517.076923,0,0,0,0,0
02/24/2020,7,8,2,1,2020,1517.076923,0,0,0,0,0
03/02/2020,8,9,3,1,2020,1517.076923,0,0,0,0,0
03/09/2020,9,10,3,1,2020,1517.076923,0,0,0,0,0
03/16/2020,10,11,3,1,2020,1517.076923,0,0,0,0,0
03/23/2020,11,12,3,1,2020,1517.076923,0,0,0,0,0
03/30/2020,12,13,3,1,2020,1517.076923,0,0,0,0,0
04/06/2020,13,14,4,2,2020,1517.076923,0,0,0,0,0
04/13/2020,14,15,4,2,2020,1517.076923,0,0,0,0,0
04/20/2020,15,16,4,2,2020,1517.076923,0,0,0,0,0
04/27/2020,16,17,4,2,2020,1517.076923,0,0,0,0,0
05/04/2020,17,18,5,2,2020,1517.076923,0,0,0,0,0
05/11/2020,18,19,5,2,2020,1517.076923,0,0,0,0,0
05/18/2020,19,20,5,2,2020,1517.076923,0,0,0,0,0
05/25/2020,20,21,5,2,2020,1517.076923,0,0,0,0,0
06/01/2020,21,22,6,2,2020,1517.076923,0,0,0,0,0
06/08/2020,22,23,6,2,2020,1517.076923,0,0,0,0,0
06/15/2020,23,24,6,2,2020,1517.076923,0,0,0,0,0
06/22/2020,24,25,6,2,2020,1517.076923,0,0,0,0,0
06/29/2020,25,26,6,2,2020,1517.076923,0,0,0,0,0
07/06/2020,26,27,7,3,2020,1517.076923,0,0,0,0,0
07/13/2020,27,28,7,3,2020,1517.076923,0,0,0,0,0
07/20/2020,28,29,7,3,2020,1517.076923,0,0,0,0,0
07/27/2020,29,30,7,3,2020,1517.076923,0,0,0,0,0
08/03/2020,30,31,8,3,2020,1517.076923,0,0,0,0,0
08/10/2020,31,32,8,3,2020,1517.076923,0,0,0,0,0
08/17/2020,32,33,8,3,2020,1517.076923,0,0,0,0,0
08/24/2020,33,34,8,3,2020,1517.076923,0,0,0,0,0
08/31/2020,34,35,8,3,2020,1517.076923,0,0,0,0,0
09/07/2020,35,36,9,3,2020,1517.076923,0,0,0,0,0
09/14/2020,36,37,9,3,2020,1517.076923,0,0,0,0,0
09/21/2020,37,38,9,3,2020,1517.076923,0,0,0,0,0
09/28/2020,38,39,9,3,2020,1517.076923,0,0,0,0,0
10/05/2020,39,40,10,4,2020,1517.076923,0,0,0,0,0
10/12/2020,40,41,10,4,2020,1517.076923,0,0,0,0,0
10/19/2020,41,42,10,4,2020,1517.076923,0,0,0,0,0
10/26/2020,42,43,10,4,2020,1517.076923,0,0,0,0,0
11/02/2020,43,44,11,4,2020,1517.076923,0,0,0,0,0
11/09/2020,44,45,11,4,2020,1517.076923,0,0,0,0,0
11/16/2020,45,46,11,4,2020,1517.076923,0,0,0,0,0
11/23/2020,46,47,11,4,2020,1517.076923,0,0,0,0,0
11/30/2020,47,48,11,4,2020,1517.076923,0,0,0,0,0
12/07/2020,48,49,12,4,2020,1517.076923,0,0,0,0,0
12/14/2020,49,50,12,4,2020,1517.076923,0,0,0,0,0
12/21/2020,50,51,12,4,2020,1517.076923,0,0,0,0,0
12/28/2020,51,52,12,4,2020,1517.076923,0,0,0,0,0

In [73]:
df.reset_index(inplace=True)

In [75]:
df

,index,Week Start,Week Number,Month,Quarter,Year,Linear,Log,Neg Exp,Power,S Origin,S Shaped
0,0,01/06/2020,1,1,1,2020,1517.076923,0,0,0,0,0
1,1,01/13/2020,2,1,1,2020,1517.076923,0,0,0,0,0
2,2,01/20/2020,3,1,1,2020,1517.076923,0,0,0,0,0
3,3,01/27/2020,4,1,1,2020,1517.076923,0,0,0,0,0
4,4,02/03/2020,5,2,1,2020,1517.076923,0,0,0,0,0
5,5,02/10/2020,6,2,1,2020,1517.076923,0,0,0,0,0
6,6,02/17/2020,7,2,1,2020,1517.076923,0,0,0,0,0
7,7,02/24/2020,8,2,1,2020,1517.076923,0,0,0,0,0
8,8,03/02/2020,9,3,1,2020,1517.076923,0,0,0,0,0
9,9,03/09/2020,10,3,1,2020,1517.076923,0,0,0,0,0
10,10,03/16/2020,11,3,1,2020,1517.076923,0,0,0,0,0
11,11,03/23/2020,12,3,1,2020,1517.076923,0,0,0,0,0
12,12,03/30/2020,13,3,1,2020,1517.076923,0,0,0,0,0
13,13,04/06/2020,14,4,2,2020,1517.076923,0,0,0,0,0
14,14,04/13/2020,15,4,2,2020,1517.076923,0,0,0,0,0
15,15,04/20/2020,16,4,2,2020,1517.076923,0,0,0,0,0
16,16,04/27/2020,17,4,2,2020,1517.076923,0,0,0,0,0
17,17,05/04/2020,18,5,2,2020,1517.076923,0,0,0,0,0
18,18,05/11/2020,19,5,2,2020,1517.076923,0,0,0,0,0
19,19,05/18/2020,20,5,2,2020,1517.076923,0,0,0,0,0
20,20,05/25/2020,21,5,2,2020,1517.076923,0,0,0,0,0
21,21,06/01/2020,22,6,2,2020,1517.076923,0,0,0,0,0
22,22,06/08/2020,23,6,2,2020,1517.076923,0,0,0,0,0
23,23,06/15/2020,24,6,2,2020,1517.076923,0,0,0,0,0
24,24,06/22/2020,25,6,2,2020,1517.076923,0,0,0,0,0
25,25,06/29/2020,26,6,2,2020,1517.076923,0,0,0,0,0
26,26,07/06/2020,27,7,3,2020,1517.076923,0,0,0,0,0
27,27,07/13/2020,28,7,3,2020,1517.076923,0,0,0,0,0
28,28,07/20/2020,29,7,3,2020,1517.076923,0,0,0,0,0
29,29,07/27/2020,30,7,3,2020,1517.076923,0,0,0,0,0
30,30,08/03/2020,31,8,3,2020,1517.076923,0,0,0,0,0
31,31,08/10/2020,32,8,3,2020,1517.076923,0,0,0,0,0
32,32,08/17/2020,33,8,3,2020,1517.076923,0,0,0,0,0
33,33,08/24/2020,34,8,3,2020,1517.076923,0,0,0,0,0
34,34,08/31/2020,35,8,3,2020,1517.076923,0,0,0,0,0
35,35,09/07/2020,36,9,3,2020,1517.076923,0,0,0,0,0
36,36,09/14/2020,37,9,3,2020,1517.076923,0,0,0,0,0
37,37,09/21/2020,38,9,3,2020,1517.076923,0,0,0,0,0
38,38,09/28/2020,39,9,3,2020,1517.076923,0,0,0,0,0
39,39,10/05/2020,40,10,4,2020,1517.076923,0,0,0,0,0
40,40,10/12/2020,41,10,4,2020,1517.076923,0,0,0,0,0
41,41,10/19/2020,42,10,4,2020,1517.076923,0,0,0,0,0
42,42,10/26/2020,43,10,4,2020,1517.076923,0,0,0,0,0
43,43,11/02/2020,44,11,4,2020,1517.076923,0,0,0,0,0
44,44,11/09/2020,45,11,4,2020,1517.076923,0,0,0,0,0
45,45,11/16/2020,46,11,4,2020,1517.076923,0,0,0,0,0
46,46,11/23/2020,47,11,4,2020,1517.076923,0,0,0,0,0
47,47,11/30/2020,48,11,4,2020,1517.076923,0,0,0,0,0
48,48,12/07/2020,49,12,4,2020,1517.076923,0,0,0,0,0
49,49,12/14/2020,50,12,4,2020,1517.076923,0,0,0,0,0
50,50,12/21/2020,51,12,4,2020,1517.076923,0,0,0,0,0
51,51,12/28/2020,52,12,4,2020,1517.076923,0,0,0,0,0